// Generated by CoffeeScript 1.8.0
// (function() {
//
// }).call(this);

var Mpeg1Muxer, child_process, events, util;

child_process = require('child_process');

util = require('util');

events = require('events');

var rtsp_process = new Array();

Mpeg1Muxer = function(options) {
  var self;
  self = this;
  this.url = options.url;
  // var args = ["-rtsp_transport", "tcp", "-i", this.url, '-f', 'mpeg1video', '-b:v', '800k', '-r', '30', '-'];
  var args = ('-rtsp_transport tcp -i ' + this.url + ' -f mpeg1video -b:v 1000k -an -r 24 -').split(' ')
  // var args = ('-rtsp_transport tcp -i ' + this.url + ' -f mpeg1video -b:v 1000k -an -r 24 -framerate 25 -probesize 10M -analyzeduration 10M -async 1 -vsync 1 -').split(' ')
  //console.log(args)
  this.stream = child_process.spawn("ffmpeg", args, {detached: true});
  rtsp_process.push(this.stream);

  this.inputStreamStarted = true;
  this.stream.stdout.on('data', function(data) {
    return self.emit('mpeg1data', data);
  });
  this.stream.stderr.on('data', function(data) {
    return self.emit('ffmpegError', data);
  });
  return this;
};

util.inherits(Mpeg1Muxer, events.EventEmitter);

module.exports = Mpeg1Muxer;
